
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClickerManDVA_DVA
{
    public static class Ext_ListIVCommander
    {
        public static List<IVCommander> SAdd(this List<IVCommander> _this, System.Byte _nVirtKey, System.String _Str)
        { return _this.Set_Add(new VKeyboard().Set(_nVirtKey: _nVirtKey, _Str: _Str)); }
        public static List<IVCommander> _LIVCommander = new List<IVCommander>()

            .SAdd(65,"A")
            .SAdd(66,"B")
            .SAdd(67,"C")
            .SAdd(68,"D")
            .SAdd(69,"E")
            .SAdd(70,"F")
            .SAdd(71,"G")
            .SAdd(72,"H")
            .SAdd(73,"I")
            .SAdd(74,"J")
            .SAdd(75,"K")
            .SAdd(76,"L")
            .SAdd(77,"M")
            .SAdd(78,"N")
            .SAdd(79,"O")
            .SAdd(80,"P")
            .SAdd(81,"Q")
            .SAdd(82,"R")
            .SAdd(83,"S")
            .SAdd(84,"T")
            .SAdd(85,"U")
            .SAdd(86,"V")
            .SAdd(87,"W")
            .SAdd(88,"X")
            .SAdd(89,"Y")
            .SAdd(90,"Z")
            .SAdd(48,"_0")
            .SAdd(49,"_1")
            .SAdd(50,"_2")
            .SAdd(51,"_3")
            .SAdd(52,"_4")
            .SAdd(53,"_5")
            .SAdd(54,"_6")
            .SAdd(55,"_7")
            .SAdd(56,"_8")
            .SAdd(57,"_9")
            .SAdd(191,"Slash")
            .SAdd(32,"Space")
            .SAdd(13,"Enter")
            .SAdd(222,"Mark")
            .SAdd(16,"Shift")
            .SAdd(112,"F1")
            .SAdd(113,"F2")
            .SAdd(114,"F3")
            .SAdd(115,"F4")
            .SAdd(116,"F5")
            .SAdd(117,"F6")
            .SAdd(118,"F7")
            .SAdd(119,"F8")
            .SAdd(120,"F9")
            .SAdd(121,"F10")
            .SAdd(122,"F11")
            .SAdd(123,"F12")
            .SAdd(8,"BACKSPACE")
            .SAdd(9,"TAB")
            .SAdd(17,"CTRL")
            .SAdd(18,"ALT")
            .SAdd(19,"PAUSE")
            .SAdd(20,"CAPSLOCK")
            .SAdd(27,"ESCAPE")
            .SAdd(33,"PAGEUP")
            .SAdd(34,"PAGEDOWN")
            .SAdd(35,"END")
            .SAdd(36,"HOME")
            .SAdd(37,"LEFT")
            .SAdd(38,"UP")
            .SAdd(39,"RIGHT")
            .SAdd(40,"DOWN")
            .SAdd(45,"INSERT")
            .SAdd(46,"DELETE")
            .SAdd(91,"LWIN")
            .SAdd(92,"RWIN")
            .SAdd(96,"NumZero")
            .SAdd(97,"NumOne")
            .SAdd(98,"NumTwo")
            .SAdd(99,"NumThree")
            .SAdd(100,"NumFor")
            .SAdd(101,"NumFive")
            .SAdd(102,"NumSix")
            .SAdd(103,"NumSeven")
            .SAdd(104,"NumEight")
            .SAdd(105,"NumNine")
            .SAdd(106,"NumStar")
            .SAdd(107,"NumPlus")
            .SAdd(109,"NumMinus")
            .SAdd(110,"NumDot")
            .SAdd(111,"NumSlash")
            .SAdd(144,"NUMLOCK")
            .SAdd(145,"SCROLLLOCK")
            .SAdd(154,"PRINTSCREEN")
            .SAdd(186,"PeriodComma")
            .SAdd(187,"Equally")
            .SAdd(188,"Сomma")
            .SAdd(189,"Minus")
            .SAdd(190,"Dot")
            .SAdd(192,"Tilda")
            .SAdd(219,"SquScobOtk")
            .SAdd(220,"ObratSlash")
            .SAdd(221,"SquScobZak")
            .SAdd(1,"MouseL")
            .SAdd(2,"MouseR")
            .SAdd(4,"MMouse")
         ;
    }
}




